package com.erickresend.verdade_ou_desafio.datas

import com.erickresend.verdade_ou_desafio.database.models.TruthModel

class DataSourceSoftTruth {

    companion object {
        fun createDataSetSoftTruth(): ArrayList<TruthModel> {
            val list = ArrayList<TruthModel>()
            list.add(TruthModel("Qual é a mania mais nojenta que você tem?"))
            list.add(TruthModel("Qual site no seu histórico de navegação te deixaria constrangido se alguém visse?"))
            list.add(TruthModel("De qual pessoa não famosa você tem inveja?"))
            list.add(TruthModel("O que você faria se tivesse uma dor de barriga em um banheiro público, mas acabasse o papel higiênico?"))
            list.add(TruthModel("Qual foi a coisa mais embaraçosa que você já fez bêbado?"))
            list.add(TruthModel("O que você adora, mas tem vergonha de admitir?"))
            list.add(TruthModel("Qual foi a coisa mais embaraçosa que já fez?"))
            list.add(TruthModel("Qual foi a pessoa mais aleatória que stalkeou nas redes sociais?"))
            list.add(TruthModel("Qual foi a última coisa que pesquisou no seu telefone?"))
            list.add(TruthModel("Quando foi a última vez que chorou e por quê?"))
            list.add(TruthModel("Já traiu algum namorado ou namorada?"))
            list.add(TruthModel("Conte uma coisa que espera que seus pais nunca descubram."))
            list.add(TruthModel("Qual é o apelido mais vergonhoso que alguém já lhe deu?"))
            list.add(TruthModel("Quem é a pessoa mais bonita da roda?"))
            list.add(TruthModel("Se tivesse que beijar um dos jogadores, quem seria?"))
            list.add(TruthModel("Qual é o seu medo mais sombrio?"))
            list.add(TruthModel("Com quem se arrepende de já ter se envolvido?"))
            list.add(TruthModel("Qual é a coisa mais estranha ou vergonhosa que já fez por dinheiro?"))
            list.add(TruthModel("Se pudesse mudar de vida com uma celebridade por um dia, com quem seria?"))
            list.add(TruthModel("Qual é a maior mentira que já contou para alguém da sua família?"))
            list.add(TruthModel("O que a maioria das pessoas pensa que é verdade sobre você, mas não é?"))
            list.add(TruthModel("Qual foi a maior conquista que já teve?"))
            list.add(TruthModel("O que você faria se fosse do sexo oposto por uma semana?"))
            list.add(TruthModel("Por que você terminou com seu último namorado ou namorada?"))
            list.add(TruthModel("Se acha bonito(a)?"))
            list.add(TruthModel("Dá uma olhada dentro do vaso sanitário antes de dar descarga?"))
            list.add(TruthModel("O que não consegue viver sem?"))
            list.add(TruthModel("Qual a maior vergonha que já passou em termos de erro em roupa?"))
            list.add(TruthModel("Que erro simples você ainda comete com frequência?"))
            list.add(TruthModel("Você tem alguma lacuna de conhecimento? Algo simples que todos sabem fazer, mas você não"))
            list.add(TruthModel("Qual a mania de limpeza que você tem e os outros acham frescura?"))
            list.add(TruthModel("Qual o talento estranho que você tem?"))
            list.add(TruthModel("Qual o passeio que você já fez que foi mais \"rolê errado\" e você só queria fugir?"))
            list.add(TruthModel("Qual a mistura de comidas estranhas de que você gosta?"))
            list.add(TruthModel("Em quem desta roda tem vontade de dar um beijo?"))
            list.add(TruthModel("O que você faria com 1 milhão de reais agora?"))
            list.add(TruthModel("Qual é a sua maior vergonha na vida?"))
            list.add(TruthModel("Se você pudesse mudar algo em você, o que seria?"))
            list.add(TruthModel("Se hoje fosse o seu último dia de vida, o que você faria?"))
            list.add(TruthModel("De 0 a 10, que nota você daria para cada um da roda em termos de beleza?"))
            list.add(TruthModel("De 0 a 10, que nota você daria para cada um da roda em termos de simpatia?"))
            list.add(TruthModel("De 0 a 10, que nota você daria para cada um da roda em termos de inteligência?"))
            list.add(TruthModel("O que os olhos não vêem o coração não sente?"))
            list.add(TruthModel("Se o mundo fosse acabar e você pudesse salvar apenas uma pessoa para sobreviver, quem seria?"))
            list.add(TruthModel("Você já beijou mais de uma pessoa no mesmo dia? Quantas?"))
            list.add(TruthModel("Você ficaria tranquilo se todo o histórico do seu WhatsApp ficasse público agora?"))
            list.add(TruthModel("Qual é o seu maior orgulho?"))
            list.add(TruthModel("Para onde você viajaria agora?"))
            list.add(TruthModel("Qual animal você gostaria de ser?"))
            list.add(TruthModel("Em uma máquina do tempo, para que época da história ou momento da sua vida você voltaria?"))
            list.add(TruthModel("Como foi a primeira vez que você beijou na boca?"))
            list.add(TruthModel("Qual característica você realmente valoria em um amigo?"))
            list.add(TruthModel("Qual é o bicho que você tem mais medo?"))
            list.add(TruthModel("Qual é o seu filme preferido?"))
            list.add(TruthModel("Você prefere ser rico ou famoso?"))
            list.add(TruthModel("Qual a pior mentira que já contaram sobre você?"))
            list.add(TruthModel("Em quais superstições você acredita?"))
            list.add(TruthModel("Qual o segredo do sucesso?"))
            list.add(TruthModel("Você acredita em vidas passadas?"))
            list.add(TruthModel("Por qual tipo de talento você gostaria de ser famoso e reconhecido?"))
            list.add(TruthModel("Qual é a comida que te faz realmente muito feliz?"))
            list.add(TruthModel("Qual é o prato que você melhor cozinha?"))
            list.add(TruthModel("Qual outro idioma você gostaria de aprender?"))
            list.add(TruthModel("O que é que o dinheiro não pode comprar?"))
            list.add(TruthModel("Qual a melhor invenção da face da terra?"))
            list.add(TruthModel("Inverno ou verão?"))
            list.add(TruthModel("Qual é a doença que você tem mais medo?"))
            list.add(TruthModel("1 ano na cadeia ou para todo o sempre com seu ex?"))
            list.add(TruthModel("Prefere saber a data ou causa da sua morte?"))
            list.add(TruthModel("O que você compraria agora com mil reais?"))
            list.add(TruthModel("Qual a coisa mais engraçada que você já fez para conquistar alguém?"))
            list.add(TruthModel("Conte sobre a maior bebedeira da sua vida."))
            list.add(TruthModel("Mulheres devem pagar menos em baladas?"))
            list.add(TruthModel("Se você tivesse que se alimentar apenas de uma comida para o resto da vida, qual seria?"))
            list.add(TruthModel("Você acredita em extraterrestres?"))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))
            list.add(TruthModel(""))

            return list
        }
    }
}